/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link UddlWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractUddlWebModule extends DefaultWebModule {

}
