/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.ui.contentassist;

import java.lang.invoke.MethodHandles;
import java.text.MessageFormat;

import org.apache.log4j.Logger;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

import com.epistimis.uddl.CLRealizationProcessor;
import com.epistimis.uddl.ConceptualEntityProcessor;
import com.epistimis.uddl.LPRealizationProcessor;
import com.epistimis.uddl.LogicalEntityProcessor;
import com.epistimis.uddl.PlatformEntityProcessor;
import com.epistimis.uddl.UddlQNP;
import com.epistimis.uddl.scoping.IndexUtilities;
import com.epistimis.uddl.uddl.LogicalComposition;
import com.epistimis.uddl.uddl.LogicalEntity;
import com.epistimis.uddl.uddl.LogicalMeasurement;
import com.epistimis.uddl.uddl.LogicalMeasurementAttribute;
import com.epistimis.uddl.uddl.LogicalMeasurementAxis;
import com.epistimis.uddl.uddl.PlatformComposableElement;
import com.epistimis.uddl.uddl.PlatformComposition;
import com.epistimis.uddl.uddl.PlatformEntity;
import com.epistimis.uddl.uddl.PlatformStruct;
import com.google.inject.Inject;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class UddlProposalProvider extends AbstractUddlProposalProvider {

	private static Logger logger = Logger.getLogger(MethodHandles.lookup().lookupClass());


	final static String ABS_MEAS_REALIZATION_ERR 	= "AbstractMeasurement {0} is not realized by any PlatformDataType";
	final static String ABS_MEAS_REALIZATION_MANY 	= "AbstractMeasurement {0} is realized by multiple PlatformDataTypes - picking one";
	final static String DEFAULT_PRECISION 			= "0.01";
	final static String INDENT 						= "\t";
	final static String MEMBER_DISPLAY_FMT 			= "{0}" ;
	final static String REALIZE_ALL 				= "<<Default Realize All>>";
	final static String STRUCT_REALIZATION_ERR 		= "PlatformStruct {0} must realize a LogicalMeasurement with 2+ axes / attributes. {1} only has {2}";
	final static String STRUCT_AXIS_FMT 			= "{0} {1} ( {2} ) ;" ;
	final static String STRUCT_ATTRIBUTE_FMT 		= "{0} {1} ( {2} ) -> {3} ;" ;
	
	@Inject UddlQNP 					qnp;
	@Inject IndexUtilities 				ndxUtil;
	@Inject	IScopeProvider 				sp;
	
	@Inject ConceptualEntityProcessor 	ceProc;
	@Inject LogicalEntityProcessor 		leProc;
	@Inject PlatformEntityProcessor 	peProc;
	
	@Inject CLRealizationProcessor		clrproc;
	@Inject LPRealizationProcessor		lprproc;
	
	@Inject CLRealizationProposalProcessor clrpproc;
	@Inject LPRealizationProposalProcessor lprpproc;
	
	 
	protected <T extends EObject,U extends EObject> QualifiedName relativeQualifiedName(T obj, U ctx) {
		return qnp.relativeQualifiedName(obj, ctx);
	}


	/** Logical -> Conceptual */
	

	/**
	 * The only way to force calling a super class method is by calling from the derived class. So we create this callback to 
	 * be used by clrpproc to force the call to the super class method
	 * @param obj
	 * @param ruleCall
	 * @param context
	 * @param acceptor
	 */
	public void superComplete_LogicalComposition(EObject obj, RuleCall ruleCall, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.complete_LogicalComposition(obj, ruleCall, context, acceptor);		
	}
	@Override
	public void complete_LogicalComposition(EObject obj, RuleCall ruleCall, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		clrpproc.complete_Composition(this,clrproc, (LogicalEntity)obj, ruleCall, context, acceptor);		
	}

//	@Override
//	public void completeLogicalComposition_Type(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
////		lookupCrossReference(((CrossReference)assignment.getTerminal()), context, acceptor);
//		clrpproc.completeComposition_Type(this, (LogicalEntity)model,  assignment, context, acceptor);
//		
//	}
	/**
	 * The only way to force calling a super class method is by calling from the derived class. So we create this callback to 
	 * be used by clrpproc to force the call to the super class method
	 * @param obj
	 * @param ruleCall
	 * @param context
	 * @param acceptor
	 */
	public void superCompleteLogicalComposition_Rolename(EObject obj, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeLogicalComposition_Rolename(obj, assignment, context, acceptor);		
	}
	@Override
	public void completeLogicalComposition_Rolename(EObject obj, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		clrpproc.completeComposition_Rolename(this, clrproc, (LogicalEntity)obj, assignment, context, acceptor);
	}

	@Override
	public void completeLogicalComposition_Realizes(EObject obj, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		clrpproc.completeComposition_Realizes(this, clrproc, (LogicalEntity)obj, assignment, context, acceptor);
	}

	/** Platform -> Logical */

	/**
	 * The only way to force calling a super class method is by calling from the derived class. So we create this callback to 
	 * be used by clrpproc to force the call to the super class method
	 * @param obj
	 * @param ruleCall
	 * @param context
	 * @param acceptor
	 */
	public void superComplete_PlatformComposition(EObject obj, RuleCall ruleCall, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.complete_PlatformComposition(obj, ruleCall, context, acceptor);		
	}
	@Override
	public void complete_PlatformComposition(EObject obj, RuleCall ruleCall, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		lprpproc.complete_Composition(this,lprproc, (PlatformEntity)obj, ruleCall, context, acceptor);

	}

//	@Override
//	public void completePlatformComposition_Type(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
////		lookupCrossReference(((CrossReference)assignment.getTerminal()), context, acceptor);
//		lprpproc.completeComposition_Type(this, (PlatformEntity)model,  assignment, context, acceptor);
//		
//	}
	/**
	 * The only way to force calling a super class method is by calling from the derived class. So we create this callback to 
	 * be used by clrpproc to force the call to the super class method
	 * @param obj
	 * @param ruleCall
	 * @param context
	 * @param acceptor
	 */
	public void superCompletePlatformComposition_Rolename(EObject obj, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completePlatformComposition_Rolename(obj, assignment, context, acceptor);		
	}
	@Override
	public void completePlatformComposition_Rolename(EObject obj, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		lprpproc.completeComposition_Rolename(this, lprproc, (PlatformEntity)obj, assignment, context, acceptor);
	}
		

	@Override
	public void completePlatformComposition_Realizes(EObject obj, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		lprpproc.completeComposition_Realizes(this, lprproc, (PlatformEntity)obj, assignment, context, acceptor);

	}

	
	
	@Override
	public void completePlatformStruct_Member(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		super.completePlatformStruct_Member(model, assignment, context, acceptor);		

		PlatformStruct ps = (PlatformStruct)model;
		// Look at the realized measurement and loop through all its axes and MeasurementAttributes
		// We must have a struct member for each. The rolename should be a lowercase version of the type name for the member (for axes)
		// or the rolename (for MeasurementAattributes). 
		
		// This can realize a LogicalMeasurement or a LogicalMeasurementAxis.
		// See idlTypeConsistentlyRealizesMeasurementAxis in constraints/platform.ocl
		// 
//		List<EPackage> pkgs = new ArrayList<>();
//		pkgs.add(UddlPackage.eINSTANCE);
		
		EObject obj = ps.getRealizes();
		if (obj instanceof LogicalMeasurement) {
			LogicalMeasurement meas = (LogicalMeasurement) ps.getRealizes();
			// The measurement must have at least 2 members + attributes
			int count = meas.getAttribute().size() + meas.getMeasurementAxis().size();
			if (count < 2) {
				String msg = MessageFormat.format(STRUCT_REALIZATION_ERR,ps.getName(),meas.getName(), count);
				logger.error(msg);
			}
			String ndent = PropUtils.indent(qnp.getFullyQualifiedName(model).getSegmentCount());
			StringBuilder insertionText = new StringBuilder();
			

			// For each axis, find all the PlatformDataTypes that realize the MeasurementAxis - each of those is a possibility
			// In order to propose the entire structure, we could find every possible combination. That could get messy. For now,
			// just pick a combination since users can edit this later.
			for (LogicalMeasurementAxis axis: meas.getMeasurementAxis()) {
				PlatformComposableElement realizingPCE = (PlatformComposableElement) lprproc.getRealizingType(/*pkgs,*/axis, ABS_MEAS_REALIZATION_ERR,ABS_MEAS_REALIZATION_MANY );
				if (realizingPCE != null) {
					StringBuilder oneProp = new StringBuilder();
					oneProp.append("\n" + ndent);
					// Set the type name
					QualifiedName n = qnp.relativeQualifiedName(realizingPCE, model);
					String displayString = MessageFormat.format(MEMBER_DISPLAY_FMT,n.getLastSegment());
					oneProp.append(MessageFormat.format(STRUCT_AXIS_FMT,n.toString(), n.getLastSegment().toLowerCase(), DEFAULT_PRECISION));
					String insertionString = oneProp.toString();
					acceptor.accept(createCompletionProposal(insertionString,displayString, null, context));
					insertionText.append(insertionString);					
				}
			}
			for (LogicalMeasurementAttribute attr: meas.getAttribute()) {
				// Get the type of the MeasurementAttribute - this should be realized by the StructMember's type
				EObject realizedAttrType = attr.getType();
				PlatformComposableElement realizingPCE = (PlatformComposableElement) lprproc.getRealizingType(/*pkgs,*/realizedAttrType, ABS_MEAS_REALIZATION_ERR,ABS_MEAS_REALIZATION_MANY );
				if (realizingPCE != null) {					
					StringBuilder oneProp = new StringBuilder();
					oneProp.append("\n" + ndent);
					// Set the type name
					QualifiedName typeName = qnp.relativeQualifiedName(realizingPCE, model);
					QualifiedName n = qnp.relativeQualifiedName(attr, model);
					String displayString = MessageFormat.format(MEMBER_DISPLAY_FMT,n.toString());
					oneProp.append(MessageFormat.format(STRUCT_ATTRIBUTE_FMT,typeName.toString(), n.getLastSegment().toLowerCase(), DEFAULT_PRECISION, n.toString()));
					String insertionString = oneProp.toString();
					acceptor.accept(createCompletionProposal(insertionString,displayString, null, context));
					insertionText.append(insertionString);			
				}
			}
			/**
			 * Always provide the Realize All choice
			 */
			acceptor.accept(createCompletionProposal(insertionText.toString(), REALIZE_ALL, null, context));
			
		} else if (obj instanceof LogicalMeasurementAxis) {
			LogicalMeasurementAxis axis = (LogicalMeasurementAxis)obj;
//		       self.oclIsTypeOf(PlatformStruct) and
//		        self.realizedMeasurementAxis().getValueTypeUnits()
//		          = self.oclAsType(PlatformStruct).member
//		                                     ->collect(type.realizes)
//		                                     ->asSet() and
//		        self.realizedMeasurementAxis().getValueTypeUnits()->size()
//		          = self.oclAsType(PlatformStruct).member
//		                                     ->collect(type.realizes)
//		                                     ->size()               
			
		}
		
	}
	
//	@Override
//	public void complete_PlatformStructMember(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
//		// Each member 
//		// Look at what this object realizes and create a proposal for each - This isn't part
//		
//	}
	
}
