/**
 * generated by Xtext 2.33.0
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conceptual Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.ConceptualDomain#getBasisEntity <em>Basis Entity</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getConceptualDomain()
 * @model
 * @generated
 */
public interface ConceptualDomain extends ConceptualElement
{
  /**
   * Returns the value of the '<em><b>Basis Entity</b></em>' reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.ConceptualBasisEntity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Basis Entity</em>' reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getConceptualDomain_BasisEntity()
   * @model
   * @generated
   */
  EList<ConceptualBasisEntity> getBasisEntity();

} // ConceptualDomain
