/**
 * generated by Xtext 2.33.0
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Enumerated Base</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalEnumeratedBase()
 * @model
 * @generated
 */
public interface LogicalEnumeratedBase extends LogicalValueType, Taxonomy
{
} // LogicalEnumeratedBase
