/**
 * generated by Xtext 2.33.0
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Measurement Conversion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalMeasurementConversion#getSource <em>Source</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalMeasurementConversion#getEquation <em>Equation</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalMeasurementConversion#getTarget <em>Target</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.LogicalMeasurementConversion#getConversionLossDescription <em>Conversion Loss Description</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalMeasurementConversion()
 * @model
 * @generated
 */
public interface LogicalMeasurementConversion extends LogicalElement
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(LogicalMeasurement)
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalMeasurementConversion_Source()
   * @model
   * @generated
   */
  LogicalMeasurement getSource();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.LogicalMeasurementConversion#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(LogicalMeasurement value);

  /**
   * Returns the value of the '<em><b>Equation</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Equation</em>' attribute list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalMeasurementConversion_Equation()
   * @model unique="false"
   * @generated
   */
  EList<String> getEquation();

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(LogicalMeasurement)
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalMeasurementConversion_Target()
   * @model
   * @generated
   */
  LogicalMeasurement getTarget();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.LogicalMeasurementConversion#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(LogicalMeasurement value);

  /**
   * Returns the value of the '<em><b>Conversion Loss Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conversion Loss Description</em>' attribute.
   * @see #setConversionLossDescription(String)
   * @see com.epistimis.uddl.uddl.UddlPackage#getLogicalMeasurementConversion_ConversionLossDescription()
   * @model
   * @generated
   */
  String getConversionLossDescription();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.LogicalMeasurementConversion#getConversionLossDescription <em>Conversion Loss Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conversion Loss Description</em>' attribute.
   * @see #getConversionLossDescription()
   * @generated
   */
  void setConversionLossDescription(String value);

} // LogicalMeasurementConversion
