/**
 * generated by Xtext 2.33.0
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.uddl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.uddl.uddl.ModelFile#getIncludes <em>Includes</em>}</li>
 *   <li>{@link com.epistimis.uddl.uddl.ModelFile#getDataModel <em>Data Model</em>}</li>
 * </ul>
 *
 * @see com.epistimis.uddl.uddl.UddlPackage#getModelFile()
 * @model
 * @generated
 */
public interface ModelFile extends EObject
{
  /**
   * Returns the value of the '<em><b>Includes</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.Include}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Includes</em>' containment reference list.
   * @see com.epistimis.uddl.uddl.UddlPackage#getModelFile_Includes()
   * @model containment="true"
   * @generated
   */
  EList<Include> getIncludes();

  /**
   * Returns the value of the '<em><b>Data Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Model</em>' containment reference.
   * @see #setDataModel(DataModel)
   * @see com.epistimis.uddl.uddl.UddlPackage#getModelFile_DataModel()
   * @model containment="true"
   * @generated
   */
  DataModel getDataModel();

  /**
   * Sets the value of the '{@link com.epistimis.uddl.uddl.ModelFile#getDataModel <em>Data Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Model</em>' containment reference.
   * @see #getDataModel()
   * @generated
   */
  void setDataModel(DataModel value);

} // ModelFile
