name: Use Artifacts and Build

on:
 workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: all-jar-artifacts
        # url:  https://github.com/bankolejohn/uddl-query-3/actions/runs/7621124781/artifacts
        # path: jar-artifacts/
        repository: bankolejohn/uddl-1a
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: 7708322012

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Downloaded Artifacts
      run: |
        # You can now use the JAR files in the 'jar-artifacts/' directory
        # for your Maven build or any other necessary tasks.
        # mvn clean install
        mvn clean install
