name: download artifact and build

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: all-jar-artifacts
                repository: bankolejohn/uddl-1a
                github-token: ${{secrets.GITHUB_TOKEN}}
                run-id: 8414074686

            - name: list files
              run: |
               pwd
               ls
               
            - name: install jfrog
              uses: jfrog/setup-jfrog-cli@v4
            - run: jf --v
           

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                       java-version: '17'
                       distribution: 'temurin'
                       cache: maven

            - name: Build code
              run: mvn clean install

            
              
